### ISSUE TITLE
Reflection pattern in SQLAlchemy causes huge performance drops

### ISSUE THREAD

**Issue by Mimameid** [dttctcs/seidr#11]
There are two cases, where we experienced performance issues.

1. Mixing method properties with fields created by reflection, causes performance problem on the `get_list` endpoint (Marshmallow is super slow with converting then queried data)
2. The relationship field causes performance issues on the `get_info` endpoint ( (Marshmallow is super slow with converting the relationship field)

**Comment by Thames1990** [comment]
Serialization of relationships might not be attributed to the reflection pattern. We have to check whether vanilla Flask AppBuilder uses marshmallow to serialize relationships.
